import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth-options";
import Groq from "groq-sdk";

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    const { content } = await request.json();
    if (!content || content.trim().length === 0) {
      return NextResponse.json({ success: false, error: "Content is required" }, { status: 400 });
    }

    const apiKey = process.env.ATS_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ success: false, error: "ATS Check API key is not configured" }, { status: 500 });
    }

    const groq = new Groq({ apiKey });
    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: `You are an advanced document analyzer and ATS evaluator.
Analyze the provided cover letter text.
1. Identify the type of letter (e.g. Job Application, Romantic Letter, Academic Inquiry, Casual Letter, Formal Complaint, etc.).
2. Determine whether the letter was likely written by a human or generated by an AI model. Estimate a probability/percentage for both (AI Score vs Human Score, which must sum up to 100%).
3. Calculate an overall ATS score or quality index (0 to 100).
4. Analyze the dominant tone (e.g. Professional, Romantic, Direct, Humble, Passionate).
5. Output 2-3 specific suggestions for improvement.
6. Provide a short, detailed analysis text.

You MUST return the output in EXACTLY the following JSON schema:
{
  "score": 85,
  "type": "Job Application",
  "aiProbability": 15,
  "humanProbability": 85,
  "readability": "Good",
  "tone": "Professional and Confident",
  "suggestions": [
    "Add more quantifiable achievements in the body paragraphs.",
    "Make the introduction paragraph more personal and engaging."
  ],
  "analysisText": "The letter maintains a high standard of professional writing, showing clear career focus, but exhibits some AI generation characteristics like repetitive transitional words."
}
Return ONLY the raw JSON object. Do not include markdown code fences (like \`\`\`json or \`\`\`), introductory remarks, or trailing explanations.`,
        },
        {
          role: "user",
          content: `Analyze this cover letter:\n\n${content}`,
        },
      ],
      model: "llama-3.3-70b-versatile",
      temperature: 0.3,
    });

    const completionText = chatCompletion.choices[0]?.message?.content?.trim() || "";
    
    // Clean up response if the model returned markdown code fences
    let cleanedText = completionText;
    if (cleanedText.startsWith("```")) {
      cleanedText = cleanedText.replace(/^```json\s*/, "").replace(/^```\s*/, "").replace(/\s*```$/, "");
    }
    
    try {
      const resultJson = JSON.parse(cleanedText);
      return NextResponse.json({ success: true, data: resultJson }, { status: 200 });
    } catch (parseError) {
      console.error("JSON parsing failed for text:", completionText);
      // Fallback response if JSON parsing fails
      return NextResponse.json({
        success: true,
        data: {
          score: 75,
          type: "Document",
          aiProbability: 50,
          humanProbability: 50,
          readability: "Moderate",
          tone: "Neutral",
          suggestions: ["Ensure formatting is consistent.", "Review tone for context."],
          analysisText: completionText
        }
      }, { status: 200 });
    }
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message || "Failed to analyze letter" }, { status: 500 });
  }
}
